### ISSUE TITLE
fix: 마이페이지,홈화면,한마디 response 형식 수정

### ISSUE THREAD

**Issue by julia-heo** [BORA-team1/backend#51]
**Feature Request**
기능 설명 :  마이페이지, 홈화면 response 형식 수정

**To-Do List**
- [x]  마이페이지 북마크, 재생목록 개수 제한 : 최대 3개
- [x]  마이페이지 follow밖으로 빼기
- [x]  홈화면 랜덤 나이대
- [x]  한마디 조회에 is_my 추가
- [x]  한마디 답글에 멘션 필드 추가
